// Code generated by "stringer -type Action -output signal_string.go"; DO NOT EDIT.

package function

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownSignal-0]
	_ = x[LONG-1]
	_ = x[SHORT-2]
	_ = x[REDUCE-3]
	_ = x[CLOSE_LONG-4]
	_ = x[CLOSE_SHORT-5]
	_ = x[STOP_LOSS-6]
	_ = x[RAISE_LONG-7]
	_ = x[RAISE_SHORT-8]
}

const _Action_name = "UnknownSignalLONGSHORTREDUCECLOSE_LONGCLOSE_SHORTSTOP_LOSSRAISE_LONGRAISE_SHORT"

var _Action_index = [...]uint8{0, 13, 17, 22, 28, 38, 49, 58, 68, 79}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
