// Code generated by "stringer -type Action"; DO NOT EDIT.

package function

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownSignal-0]
	_ = x[LONG-1]
	_ = x[SHORT-2]
	_ = x[REDUCE-3]
	_ = x[CLOSE-4]
	_ = x[STOP_LOSS-5]
}

const _Action_name = "UnknownSignalLONGSHORTREDUCECLOSESTOP_LOSS"

var _Action_index = [...]uint8{0, 13, 17, 22, 28, 33, 42}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
