// Code generated by "stringer -type Signal"; DO NOT EDIT.

package function

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownSignal-0]
	_ = x[LONG-1]
	_ = x[SHORT-2]
	_ = x[REDUCE-3]
	_ = x[CLOSE-4]
	_ = x[STOP_LOSS-5]
}

const _Signal_name = "UnknownSignalLONGSHORTREDUCECLOSESTOP_LOSS"

var _Signal_index = [...]uint8{0, 13, 17, 22, 28, 33, 42}

func (i Signal) String() string {
	if i < 0 || i >= Signal(len(_Signal_index)-1) {
		return "Signal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Signal_name[_Signal_index[i]:_Signal_index[i+1]]
}
